### ISSUE TITLE
Vertaisarviointi

### ISSUE THREAD

**Issue by kodtld** [HeljaeRaeisaenen/tiralabra23#1]
_Ladattu laitteelle 19.02.2023 - 14:30_

Koodista huomaa että projekti on edennyt hyvää tahtia ja on ydintoiminnaltaan valmis. Koodin eri aihealueet ovat jaettu selkeästi eri tiedostoihin ja koodi on helppolukuista.

**Kommentit**

Testikattavuus oli yleisesti hyvä ja testit suoriutuivat. Parilla lisätestillä markov_processin testikattavuus saataisiin korkeammaksi.
Projektin repositorio oli siisti, vaikka commitit olisivat voineet olla hieman kuvaavammin nimettyjä. Myös ".coveragerc" tiedoston olisi voinut sisällyttä .gitignoreen.
Niinkuin sanottua ohjelma toimi erinomaisesti ja generaatioiden laadulliset erot olivat selkeästi huomattavissa vaihtamalla markovin ketjun astetta. Mielestäni olisi hyvä idea että lauseita olisi mahdollista generoida myös enemmän kuin yhden .txt tiedoston pohjalta jotta vaihtelu olisi suurempaa.
Pylint testeistä projekti sai arvosanan 8.67, voisi olla hyvä idea lisätä pylint tarkistus main.yml pipelineen.

Kokonaisuudessaan projekti oli oikein hienosti toteutettu ja toimi hyvin. Kehityskohtia ei mielestäni esiintynyt hirveästi.
Hyvää työtä!

**Comment by HeljaeRaeisaenen** [comment]
Kiitos neuvoista, otan ne huomioon :)
